from django.contrib.auth.hashers import BasePasswordHasher
from werkzeug.security import check_password_hash, generate_password_hash

class WerkzeugPasswordHasher(BasePasswordHasher):
    """
    Bridge password hasher that allows Django to verify password hashes 
    generated by Flask / Werkzeug security helpers.
    """
    algorithm = "werkzeug"

    def encode(self, password, salt):
        # Delegate hashing to Werkzeug's default hasher
        return generate_password_hash(password)

    def verify(self, password, encoded):
        # Werkzeug hashes can be scrypt or pbkdf2
        return check_password_hash(encoded, password)

    def safe_summary(self, encoded):
        return {
            "algorithm": self.algorithm,
        }
