# Generated by Django 6.0.6 on 2026-07-13 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('normal_range', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tests', models.ManyToManyField(db_table='Test_Package_Tests', related_name='packages', to='tests.test')),
            ],
            options={
                'db_table': 'Test_Packages',
            },
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('normal_range', models.CharField(blank=True, default='', max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('formula', models.TextField(blank=True, null=True)),
                ('parameter_type', models.CharField(default='text', max_length=50)),
                ('test', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='tests.test')),
            ],
            options={
                'db_table': 'Test_Parameters',
            },
        ),
    ]
